# fly.toml app configuration file generated for akar-kuadrat-api on 2023-10-02T22:00:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "akar-kuadrat-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
